logging:
  level:
    org:
      springframework:
        security:
          web: DEBUG
dungeon:
  map:
    width: 30
    height: 30
  elements:
    - id: A
      x: 3
      y: 3
      speed: 300
      direction: S
    - id: B
      x: 8
      y: 3
      speed: 400
      direction: SE
    - id: C
      x: 13
      y: 3
      speed: 500
      direction: SW
    - id: D
      x: 18
      y: 3
      speed: 600
      direction: S
    - id: E
      x: 21
      y: 3
      speed: 700
      direction: SE
    - id: F
      x: 24
      y: 3
      speed: 800
      direction: SW
    - id: G
      x: 27
      y: 3
      speed: 900
      direction: S
